// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.21.0
// 	protoc        v3.5.1
// source: gw.proto

package pb

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type GWMsgEnum int32

const (
	GWMsgEnum_world GWMsgEnum = 0
	GWMsgEnum_game  GWMsgEnum = 1
)

// Enum value maps for GWMsgEnum.
var (
	GWMsgEnum_name = map[int32]string{
		0: "world",
		1: "game",
	}
	GWMsgEnum_value = map[string]int32{
		"world": 0,
		"game":  1,
	}
)

func (x GWMsgEnum) Enum() *GWMsgEnum {
	p := new(GWMsgEnum)
	*p = x
	return p
}

func (x GWMsgEnum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GWMsgEnum) Descriptor() protoreflect.EnumDescriptor {
	return file_gw_proto_enumTypes[0].Descriptor()
}

func (GWMsgEnum) Type() protoreflect.EnumType {
	return &file_gw_proto_enumTypes[0]
}

func (x GWMsgEnum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GWMsgEnum.Descriptor instead.
func (GWMsgEnum) EnumDescriptor() ([]byte, []int) {
	return file_gw_proto_rawDescGZIP(), []int{0}
}

type GWMsgRetCode_RetCode int32

const (
	GWMsgRetCode_RetCode_OK           GWMsgRetCode_RetCode = 0
	GWMsgRetCode_RetCode_Err          GWMsgRetCode_RetCode = 1
	GWMsgRetCode_RetCode_GWMsgEnumErr GWMsgRetCode_RetCode = 2
	GWMsgRetCode_RetCode_RouterErr    GWMsgRetCode_RetCode = 3
)

// Enum value maps for GWMsgRetCode_RetCode.
var (
	GWMsgRetCode_RetCode_name = map[int32]string{
		0: "RetCode_OK",
		1: "RetCode_Err",
		2: "RetCode_GWMsgEnumErr",
		3: "RetCode_RouterErr",
	}
	GWMsgRetCode_RetCode_value = map[string]int32{
		"RetCode_OK":           0,
		"RetCode_Err":          1,
		"RetCode_GWMsgEnumErr": 2,
		"RetCode_RouterErr":    3,
	}
)

func (x GWMsgRetCode_RetCode) Enum() *GWMsgRetCode_RetCode {
	p := new(GWMsgRetCode_RetCode)
	*p = x
	return p
}

func (x GWMsgRetCode_RetCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GWMsgRetCode_RetCode) Descriptor() protoreflect.EnumDescriptor {
	return file_gw_proto_enumTypes[1].Descriptor()
}

func (GWMsgRetCode_RetCode) Type() protoreflect.EnumType {
	return &file_gw_proto_enumTypes[1]
}

func (x GWMsgRetCode_RetCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GWMsgRetCode_RetCode.Descriptor instead.
func (GWMsgRetCode_RetCode) EnumDescriptor() ([]byte, []int) {
	return file_gw_proto_rawDescGZIP(), []int{1, 0}
}

//根据gwMsgType和router来路由消息
type GWMsgRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GwMsgType GWMsgEnum `protobuf:"varint,1,opt,name=gwMsgType,proto3,enum=gwpb.GWMsgEnum" json:"gwMsgType,omitempty"`
	Router    string    `protobuf:"bytes,2,opt,name=router,proto3" json:"router,omitempty"`
	MsgData   []byte    `protobuf:"bytes,3,opt,name=msgData,proto3" json:"msgData,omitempty"` //转发的消息
}

func (x *GWMsgRequest) Reset() {
	*x = GWMsgRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gw_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GWMsgRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GWMsgRequest) ProtoMessage() {}

func (x *GWMsgRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gw_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GWMsgRequest.ProtoReflect.Descriptor instead.
func (*GWMsgRequest) Descriptor() ([]byte, []int) {
	return file_gw_proto_rawDescGZIP(), []int{0}
}

func (x *GWMsgRequest) GetGwMsgType() GWMsgEnum {
	if x != nil {
		return x.GwMsgType
	}
	return GWMsgEnum_world
}

func (x *GWMsgRequest) GetRouter() string {
	if x != nil {
		return x.Router
	}
	return ""
}

func (x *GWMsgRequest) GetMsgData() []byte {
	if x != nil {
		return x.MsgData
	}
	return nil
}

type GWMsgRetCode struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GWMsgRetCode) Reset() {
	*x = GWMsgRetCode{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gw_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GWMsgRetCode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GWMsgRetCode) ProtoMessage() {}

func (x *GWMsgRetCode) ProtoReflect() protoreflect.Message {
	mi := &file_gw_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GWMsgRetCode.ProtoReflect.Descriptor instead.
func (*GWMsgRetCode) Descriptor() ([]byte, []int) {
	return file_gw_proto_rawDescGZIP(), []int{1}
}

//gateway返回消息
type GWMsgResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GwMsgType GWMsgEnum     `protobuf:"varint,1,opt,name=gwMsgType,proto3,enum=gwpb.GWMsgEnum" json:"gwMsgType,omitempty"`
	RetCode   *GWMsgRetCode `protobuf:"bytes,2,opt,name=RetCode,proto3" json:"RetCode,omitempty"`
	MsgData   []byte        `protobuf:"bytes,3,opt,name=msgData,proto3" json:"msgData,omitempty"` //具体返回的消息
}

func (x *GWMsgResponse) Reset() {
	*x = GWMsgResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gw_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GWMsgResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GWMsgResponse) ProtoMessage() {}

func (x *GWMsgResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gw_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GWMsgResponse.ProtoReflect.Descriptor instead.
func (*GWMsgResponse) Descriptor() ([]byte, []int) {
	return file_gw_proto_rawDescGZIP(), []int{2}
}

func (x *GWMsgResponse) GetGwMsgType() GWMsgEnum {
	if x != nil {
		return x.GwMsgType
	}
	return GWMsgEnum_world
}

func (x *GWMsgResponse) GetRetCode() *GWMsgRetCode {
	if x != nil {
		return x.RetCode
	}
	return nil
}

func (x *GWMsgResponse) GetMsgData() []byte {
	if x != nil {
		return x.MsgData
	}
	return nil
}

var File_gw_proto protoreflect.FileDescriptor

var file_gw_proto_rawDesc = []byte{
	0x0a, 0x08, 0x67, 0x77, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x67, 0x77, 0x70, 0x62,
	0x22, 0x6f, 0x0a, 0x0c, 0x47, 0x57, 0x4d, 0x73, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x2d, 0x0a, 0x09, 0x67, 0x77, 0x4d, 0x73, 0x67, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x0f, 0x2e, 0x67, 0x77, 0x70, 0x62, 0x2e, 0x47, 0x57, 0x4d, 0x73, 0x67,
	0x45, 0x6e, 0x75, 0x6d, 0x52, 0x09, 0x67, 0x77, 0x4d, 0x73, 0x67, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x16, 0x0a, 0x06, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x73, 0x67, 0x44, 0x61,
	0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x6d, 0x73, 0x67, 0x44, 0x61, 0x74,
	0x61, 0x22, 0x6b, 0x0a, 0x0c, 0x47, 0x57, 0x4d, 0x73, 0x67, 0x52, 0x65, 0x74, 0x43, 0x6f, 0x64,
	0x65, 0x22, 0x5b, 0x0a, 0x07, 0x52, 0x65, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x0e, 0x0a, 0x0a,
	0x52, 0x65, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x5f, 0x4f, 0x4b, 0x10, 0x00, 0x12, 0x0f, 0x0a, 0x0b,
	0x52, 0x65, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x5f, 0x45, 0x72, 0x72, 0x10, 0x01, 0x12, 0x18, 0x0a,
	0x14, 0x52, 0x65, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x5f, 0x47, 0x57, 0x4d, 0x73, 0x67, 0x45, 0x6e,
	0x75, 0x6d, 0x45, 0x72, 0x72, 0x10, 0x02, 0x12, 0x15, 0x0a, 0x11, 0x52, 0x65, 0x74, 0x43, 0x6f,
	0x64, 0x65, 0x5f, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x45, 0x72, 0x72, 0x10, 0x03, 0x22, 0x86,
	0x01, 0x0a, 0x0d, 0x47, 0x57, 0x4d, 0x73, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x2d, 0x0a, 0x09, 0x67, 0x77, 0x4d, 0x73, 0x67, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x0f, 0x2e, 0x67, 0x77, 0x70, 0x62, 0x2e, 0x47, 0x57, 0x4d, 0x73, 0x67,
	0x45, 0x6e, 0x75, 0x6d, 0x52, 0x09, 0x67, 0x77, 0x4d, 0x73, 0x67, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x2c, 0x0a, 0x07, 0x52, 0x65, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x12, 0x2e, 0x67, 0x77, 0x70, 0x62, 0x2e, 0x47, 0x57, 0x4d, 0x73, 0x67, 0x52, 0x65, 0x74,
	0x43, 0x6f, 0x64, 0x65, 0x52, 0x07, 0x52, 0x65, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x6d, 0x73, 0x67, 0x44, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07,
	0x6d, 0x73, 0x67, 0x44, 0x61, 0x74, 0x61, 0x2a, 0x20, 0x0a, 0x09, 0x47, 0x57, 0x4d, 0x73, 0x67,
	0x45, 0x6e, 0x75, 0x6d, 0x12, 0x09, 0x0a, 0x05, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x10, 0x00, 0x12,
	0x08, 0x0a, 0x04, 0x67, 0x61, 0x6d, 0x65, 0x10, 0x01, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x3b, 0x70,
	0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_gw_proto_rawDescOnce sync.Once
	file_gw_proto_rawDescData = file_gw_proto_rawDesc
)

func file_gw_proto_rawDescGZIP() []byte {
	file_gw_proto_rawDescOnce.Do(func() {
		file_gw_proto_rawDescData = protoimpl.X.CompressGZIP(file_gw_proto_rawDescData)
	})
	return file_gw_proto_rawDescData
}

var file_gw_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_gw_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_gw_proto_goTypes = []interface{}{
	(GWMsgEnum)(0),            // 0: gwpb.GWMsgEnum
	(GWMsgRetCode_RetCode)(0), // 1: gwpb.GWMsgRetCode.RetCode
	(*GWMsgRequest)(nil),      // 2: gwpb.GWMsgRequest
	(*GWMsgRetCode)(nil),      // 3: gwpb.GWMsgRetCode
	(*GWMsgResponse)(nil),     // 4: gwpb.GWMsgResponse
}
var file_gw_proto_depIdxs = []int32{
	0, // 0: gwpb.GWMsgRequest.gwMsgType:type_name -> gwpb.GWMsgEnum
	0, // 1: gwpb.GWMsgResponse.gwMsgType:type_name -> gwpb.GWMsgEnum
	3, // 2: gwpb.GWMsgResponse.RetCode:type_name -> gwpb.GWMsgRetCode
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_gw_proto_init() }
func file_gw_proto_init() {
	if File_gw_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_gw_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GWMsgRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gw_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GWMsgRetCode); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gw_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GWMsgResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_gw_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_gw_proto_goTypes,
		DependencyIndexes: file_gw_proto_depIdxs,
		EnumInfos:         file_gw_proto_enumTypes,
		MessageInfos:      file_gw_proto_msgTypes,
	}.Build()
	File_gw_proto = out.File
	file_gw_proto_rawDesc = nil
	file_gw_proto_goTypes = nil
	file_gw_proto_depIdxs = nil
}
